# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

unless ARGV.any? { |a| a =~ /^gems/ } # Don't load anything when running the gems:* tasks

  begin
    require 'cucumber/rake/task'

    namespace :cucumber do
      if ARGV.any? { |a| a.downcase =~ /^cucumber/ }

        Cucumber::Rake::Task.new({:ok => 'test:prepare'}, 'Run all features') do |t|
          #t.binary = vendored_cucumber_bin # If nil, the gem's binary is used.
          t.fork = true # You may get faster startup if you set this to false
          t.profile = 'default'
        end

        %w(setup verify wip rerun test).each do |task|
          Cucumber::Rake::Task.new({task.to_sym => 'test:prepare'}, "Run features with #{task} profile.") do |t|
            #t.binary = vendored_cucumber_bin # If nil, the gem's binary is used.
            t.fork = true # You may get faster startup if you set this to false
            t.profile = task
          end
        end

        desc 'Run all features'
        task :all => [:ok, :wip]

        task :statsetup do
          require 'rails/code_statistics'
          ::STATS_DIRECTORIES << %w(Cucumber\ features features) if File.exist?('features')
          ::CodeStatistics::TEST_TYPES << "Cucumber features" if File.exist?('features')
        end
      end
    end
    desc 'Alias for cucumber:ok'
    task :cucumber => 'cucumber:ok'

    task :default => :cucumber

    task :features => :cucumber do
      STDERR.puts "*** The 'features' task is deprecated. See rake -T cucumber ***"
    end

    # In case we don't have the generic Rails test:prepare hook, append a no-op task that we can depend upon.
    task 'test:prepare' do
    end

    task :stats => 'cucumber:statsetup'
  rescue LoadError
    desc 'cucumber rake task not available (cucumber not installed)'
    task :cucumber do
      abort 'Cucumber rake task is not available. Be sure to install cucumber as a gem or plugin'
    end
  end

end
